# Generated by Django 4.2.6 on 2024-10-08 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductosStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boletas",
            fields=[
                ("id_boleta", models.AutoField(primary_key=True, serialize=False)),
                ("total_boleta", models.IntegerField()),
                ("total_descuento", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "boletas",
            },
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_FK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ventas",
            },
        ),
        migrations.CreateModel(
            name="DetalleBoletas",
            fields=[
                (
                    "id_detalle_boleta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.IntegerField()),
                ("total", models.IntegerField()),
                ("producto_nombre", models.CharField(max_length=255)),
                ("producto_precio", models.IntegerField()),
                (
                    "boleta_FK",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VentasStoreApp.boletas",
                    ),
                ),
                (
                    "producto_FK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ProductosStoreApp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "detalleboleta",
            },
        ),
        migrations.AddField(
            model_name="boletas",
            name="venta_FK",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="VentasStoreApp.ventas",
            ),
        ),
    ]
