# Generated by Django 4.2.6 on 2024-10-08 17:43

import UsuariosStoreApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_position", models.CharField(max_length=45, unique=True)),
                (
                    "permission_code",
                    models.CharField(
                        choices=[
                            ("ADMIN", "admin"),
                            ("RESTRICTED", "restricted"),
                            ("MANAGER", "manager"),
                        ],
                        default="RESTRICTED",
                        max_length=25,
                    ),
                ),
            ],
            options={
                "db_table": "position",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=UsuariosStoreApp.models.profile_picture_path,
                    ),
                ),
                ("telefono_user", models.CharField(max_length=15)),
                (
                    "position_FK",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UsuariosStoreApp.position",
                    ),
                ),
                (
                    "user_FK",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "ordering": ["-id"],
            },
        ),
    ]
