# Generated by Django 4.2.6 on 2024-10-08 17:43

import DatosEmpresaStoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosEmpresa",
            fields=[
                (
                    "id_datos_empresa",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_empresa", models.CharField(max_length=45)),
                ("rut_empresa", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=64)),
                ("telefono", models.CharField(max_length=15)),
                ("comuna", models.CharField(max_length=45)),
                ("direccion_empresa", models.CharField(max_length=45)),
                ("razon_social", models.CharField(max_length=64)),
                ("actividad_economica", models.CharField(max_length=64)),
                ("IVA", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=DatosEmpresaStoreApp.models.empresa_picture_path,
                    ),
                ),
                (
                    "margen_global",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
            ],
            options={
                "db_table": "datosempresa",
            },
        ),
    ]
