# Generated by Django 4.2.6 on 2024-10-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ProveedoresStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compras",
            fields=[
                ("id_compras", models.AutoField(primary_key=True, serialize=False)),
                ("num_documento", models.CharField(max_length=15, unique=True)),
                ("fecha", models.DateField()),
                ("total", models.IntegerField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("FACTURA", "Factura"), ("BOLETA", "Boleta")],
                        default="BOLETA",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[
                            ("CON IMPUESTO", "Con Impuesto"),
                            ("SIN IMPUESTO", "Sin Impuesto"),
                        ],
                        default="CON IMPUESTO",
                        max_length=20,
                    ),
                ),
                (
                    "proveedor_FK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ProveedoresStoreApp.proveedor",
                    ),
                ),
            ],
            options={
                "db_table": "compras",
            },
        ),
    ]
