# Generated by Django 4.2.6 on 2024-10-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ProductosStoreApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promociones",
            fields=[
                ("id_promocion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("descuento", models.IntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "producto_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductosStoreApp.producto",
                    ),
                ),
            ],
            options={
                "db_table": "promociones",
            },
        ),
    ]
