# Generated by Django 4.2.6 on 2024-10-08 17:43

import ProductosStoreApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_categoria", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_producto", models.CharField(max_length=45, unique=True)),
                ("descripcion_producto", models.CharField(max_length=45)),
                ("precio_bruto_producto", models.IntegerField()),
                ("precio_venta", models.IntegerField(default=10)),
                (
                    "margen_ganancia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=ProductosStoreApp.models.dynamic_upload_path,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=3, default=10.0, max_digits=10),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "tipo_medida",
                    models.CharField(
                        choices=[("UNIDAD", "Unidad"), ("KILO", "Kilo")],
                        default="UNIDAD",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[("IVA", "IVA"), ("EXENTO", "EXENTO")],
                        default="IVA",
                        max_length=20,
                    ),
                ),
                (
                    "categoria_FK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ProductosStoreApp.categoria",
                    ),
                ),
                (
                    "usuario_FK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "producto",
            },
        ),
    ]
